version: "2" 

services:
  vacation-db: 
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_DATABASE: vacation
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3333:3306

  vacation-app:
    build: app/app/
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://vacation-db:3306/vacation?serverTimezone=UTC
    depends_on:
      - vacation-db
